-- INFO
-- insert this file first after creating the database
-- This file has been generated by exporting SQL from astah professional
-- This file uses syntax compatible with postgreSQL

CREATE TABLE crime (
 crime_id SERIAL NOT NULL,
 crime VARCHAR(100) NOT NULL
);

ALTER TABLE crime ADD CONSTRAINT PK_crime PRIMARY KEY (crime_id);


CREATE TABLE district (
 district_id SERIAL NOT NULL,
 district VARCHAR(100) NOT NULL
);

ALTER TABLE district ADD CONSTRAINT PK_district PRIMARY KEY (district_id);


CREATE TABLE year (
 year_id SERIAL NOT NULL,
 year INT NOT NULL
);

ALTER TABLE year ADD CONSTRAINT PK_year PRIMARY KEY (year_id);


CREATE TABLE data (
 year_id INT NOT NULL,
 district_id INT NOT NULL,
 crime_id INT NOT NULL,
 value INT
);

ALTER TABLE data ADD CONSTRAINT PK_data PRIMARY KEY (year_id,district_id,crime_id);


ALTER TABLE data ADD CONSTRAINT FK_data_0 FOREIGN KEY (year_id) REFERENCES year (year_id);
ALTER TABLE data ADD CONSTRAINT FK_data_1 FOREIGN KEY (district_id) REFERENCES district (district_id);
ALTER TABLE data ADD CONSTRAINT FK_data_2 FOREIGN KEY (crime_id) REFERENCES crime (crime_id);


